### PR TITLE
Compressed main assets losslessly

### PR DESCRIPTION
**Pull request by Michael18751**

### CODE REVIEW

**Comment by AaronFeng753** [comment]
No offense, I appreciate your help, but this is 2020, so I don't anybody's internet connection will be affected by just a few kilobytes. And I certainly don't want my icon file to be compressed.
STOP SEND ANY PULL REQUEST RELATED TO COMPRESSED IMAGES, OKAY?

**Comment by AaronFeng753** [comment]
Btw, about that English grammar error problem, just create an issue and tell me where the problem is. There are no way to fix those error without chang the source code. So I wanna do it myself so nothing will gose wrong. 
And if the error is not very serious, just ignore it. I know my English is not great but I do think most people can understand what I am trying to say.

**Comment by Michael18751** [comment]
Yeah, I just want to help, thats all

**Comment by AaronFeng753** [comment]
> Yeah, I just want to help, that's all (sorry) lossless compression does nothing to the quality of the images. You can look at both of them side by side. They will be exactly the same.
> 
> As for the English language, there are many things to point out (no offense). But it is too much to make an issue on it. If you want to send me the code for the English language, I can edit that if you want me too. If not then just ignore this message.
> 
> What I could also do is make a pull request for a new (language_English.ts) file and you do not need to accept that but you can see all of the changes I made to it and move those changes to the source if you would like to.
> 
> I'm not saying it's bad enough, but I'm here if you would like me to improve it.

there are no code just for English language. the English text is scattered all around the code. because I don't want any compatibility issue, so this program's original language is English, not Chinese. therefore, there is no English language file, because it dosen't need to be translate to English

**Pull request closed without merging**
