### PR TITLE
English localization fixes

### PR DESCRIPTION
**Pull request by Nova-Aurora**
Fixing some english translations that sounded weird. I can't test if this breaks anything since I don't know how to build, sorry.

### CODE REVIEW

**Comment by Nova-Aurora** [comment]
Went back into your past pull requests and realized you aren't taking pull requests on language_english.

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/pull/171#issuecomment-722686736

**Comment by AaronFeng753** [comment]
✅ https://github.com/AaronFeng753/Waifu2x-Extension-GUI/commit/9eeffa3929330c8dda6d6690476dfa58f5d207de

**Comment by Nova-Aurora** [comment]
Nice! Thank you for being so quick in responding to the community!

**Pull request closed without merging**
